// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22.4.2026, 15:15:50
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/morit/MyCode/mindcoded/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/plugins/**/*.{js,ts,mjs}","C:/Users/morit/MyCode/mindcoded/composables/**/*.{js,ts,mjs}","C:/Users/morit/MyCode/mindcoded/utils/**/*.{js,ts,mjs}","C:/Users/morit/MyCode/mindcoded/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/mindcoded/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;